language: python
python:
  - 3.6
services:
  - postgresql
env:
  -DEBUG=False
  -DB=postgresql
  -DB_NAME=cgen_db
  -DB_USER=jboss
  -DB_PASSWORD=jboss
  -DB_HOST=127.0.0.1
  -DB_PORT=5432
  -SECRET_KEY=YOUR-SECRET-KEY
  -GOOGLE_OAUTH2_KEY=YOUR-SECRET-KEY
  -GOOGLE_OAUTH2_SECRET=YOUR-SECRET-KEY
  -FACEBOOK_KEY=YOUR-SECRET-KEY
  -FACEBOOK_SECRET=YOUR-SECRET-KEY
  -TWITTER_KEY=YOUR-SECRET-KEY
  -TWITTER_SECRET=YOUR-SECRET-KEY
  -ALLOWED_HOSTS=.localhost, .herokuapp.com
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE USER jboss WITH CREATEUSER PASSWORD 'jboss';" -U postgres
  - psql -c "ALTER USER jboss CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE cgen_db;" -U postgres
  - psql -c "GRANT ALL ON DATABASE cgen_db TO jboss;" -U postgres
script: 
  - python manage.py makemigrations api
  - python manage.py migrate
  