language: python
python:
 - "3.6"
  services: # => 3
      - mysql
      
      env: # => 4
      -DJANGO=1.8 DB=mysql
      
install: pip install -r requirements.txt

  before_script: # => 6
      - mysql -e 'create database test;' -u root
script:
  - python manage.py test



